name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (publish with --dry-run flag)'
        type: boolean
        default: true
      tag:
        description: 'NPM tag (latest, beta, alpha, etc.)'
        type: string
        default: 'latest'

jobs:
  manual-publish:
    name: Manual Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test:all

      - name: Build packages
        run: pnpm run build:all

      - name: Publish to NPM (Dry Run)
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: |
          cd packages/next-navigation
          npm publish --dry-run --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          cd packages/next-navigation
          npm publish --access public --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Summary
        run: |
          echo "## Publish Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Package**: @vooteam/next-navigation" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: ${{ github.event.inputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Dry Run**: ${{ github.event.inputs.dry_run }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event.inputs.dry_run }}" = "false" ]; then
            echo "- **Status**: ✅ Published to NPM" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Status**: 🧪 Dry run completed" >> $GITHUB_STEP_SUMMARY
          fi
